inherit_gem:
  rubocop-policy:
    - rubocop-default.yml

Layout/LineLength:
  Max: 1000

Style/StringConcatenation:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Style/NegatedIf:
  Enabled: false

Minitest/RefuteFalse:
  Enabled: false

Minitest/RefuteEqual:
  Enabled: false
