services:
  api:
    depends_on:
      - redis-count
    environment:
      REDIS_COUNT_HOST: redis-count

  redis-count:
    image: redis:${REDIS_VERSION:-7-alpine}
    volumes:
      - ./docker/redis-count:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: CMD redis-cli --raw incr ping
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
