version: '3.3'
services:
  api:
    build: .
    image: ghcr.io/cartoway/router-api:${CARTOROUTE_VERSION:-master}
    ports:
      - "8082:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - .:/srv/app
      - ./docker/access.rb:/srv/app/config/access.rb
      - ./docker/production.rb:/srv/app/config/environments/production.rb
      - ./docker/production.rb:/srv/app/config/environments/development.rb
      - ./docker/poly:/srv/app/poly
    depends_on:
      - redis-cache
    environment:
      REDIS_HOST: redis-cache
      APP_ENV: ${APP_ENV:-development}
      HERE8_APIKEY: ${HERE8_APIKEY}
      SENTRY_DSN: ${SENTRY_DSN}
    command: bundle exec puma -v -p 80 --pidfile 'tmp/server.pid'
    restart: unless-stopped

  redis-cache:
    image: redis:${REDIS_VERSION:-7-alpine}
    command: redis-server --save ""
    restart: unless-stopped
