services:
  postgis:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    volumes:
      - postgis:/var/lib/postgres
      - ./docker/osrm/landuses:/landuses
    healthcheck:
      test: pg_isready
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5

  redis-build:
    image: redis:${REDIS_VERSION:-7-alpine}
    healthcheck:
      test: redis-cli --raw incr ping
      start_interval: 1s
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgis:
