version: '3.3'
services:
  api:
    build: .
    image: router-api:${CARTOROUTE_VERSION:-latest}
    ports:
      - "8082:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - .:/srv/app
      - ./docker/access.rb:/srv/app/config/access.rb
      - ./docker/production.rb:/srv/app/config/environments/production.rb
      - ./docker/production.rb:/srv/app/config/environments/development.rb
      - ./docker/poly:/srv/app/poly
    links:
      - redis-cache
      - redis-count
      - osrm-car-iceland
    environment:
      REDIS_HOST: redis-cache
      REDIS_COUNT_HOST: redis-count
      APP_ENV: production # Switch to "development" for more traces
    command: bundle exec puma -v -p 80 --pidfile 'tmp/server.pid'
    restart: unless-stopped

  otp-bordeaux:
    build:
      context: docker/otp
    environment:
      GRAPH: bordeaux
    ports:
      - "7001:7000"
    volumes:
      - ./docker/otp/data:/srv/otp/data
    restart: unless-stopped

  osrm-car-iceland:
    build:
      context: docker/osrm
    environment:
      BASENAME: car-iceland
      PBF_URL: http://download.geofabrik.de/europe/iceland-latest.osm.pbf
      PROFILE: /srv/osrm/profiles/car/car.lua
    volumes:
      - ./docker/osrm/data:/srv/osrm/data
      - ./docker/osrm/profiles:/srv/osrm/profiles
      - /dev/log:/dev/log
    restart: unless-stopped

  redis-cache:
    image: redis:${REDIS_VERSION:-7-alpine}
    command: redis-server --save ""
    restart: unless-stopped

  redis-count:
    image: redis:${REDIS_VERSION:-7-alpine}
    volumes:
      - ./docker/redis-count:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
