x-graphhopper: &x-graphhopper
  build:
    context: docker/graphhopper
  image: ghcr.io/cartoway/router-api-graphhopper:${CARTOROUTE_VERSION:-master}
  volumes:
    - ./docker/graphhopper/data:/srv/graphhopper/data
    - ./docker/graphhopper/config.yaml:/opt/app/config.yaml
  restart: unless-stopped

services:
  api:
    depends_on:
      - graphhopper

  graphhopper:
    <<: *x-graphhopper
    environment:
      BASENAME: car-iceland
      PBF_URLS: http://download.geofabrik.de/europe/iceland-latest.osm.pbf http://download.geofabrik.de/europe/andorra-latest.osm.pbf
