version: '3.3'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8082:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ..:/srv/app
      - ./access.rb:/srv/app/config/access.rb
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./production.rb:/srv/app/config/environments/development.rb
      - ./poly:/srv/app/poly
    links:
      - redis-cache
      - redis-count
      - osrm-car-iceland
    environment:
      REDIS_HOST: redis-cache
      REDIS_COUNT_HOST: redis-count
      APP_ENV: production # Switch to "development" for more traces
    command: bundle exec puma -v -p 80 --pidfile 'tmp/server.pid'
    restart: unless-stopped

  otp-bordeaux:
    build:
      context: otp
    environment:
      GRAPH: bordeaux
    ports:
      - "7001:7000"
    volumes:
      - ./otp/data:/srv/otp/data
    restart: unless-stopped

  osrm-car-iceland:
    build:
      context: osrm
    environment:
      BASENAME: car-iceland
    volumes:
      - ./osrm/data:/srv/osrm/data
      - /dev/log:/dev/log
    restart: unless-stopped

  redis-cache:
    image: redis:${REDIS_VERSION:-7-alpine}
    command: redis-server --save ""
    restart: unless-stopped

  redis-count:
    image: redis:${REDIS_VERSION:-7-alpine}
    volumes:
      - ./data-count:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
