#!/bin/bash

set -e

export NODE_MODULES=/opt/node_modules
export NODE_CONFIG_DIR=/opt/node_modules/osrm-isochrone-server/config/

cd /opt
exec npx osrm-isochrone-server --port 6000 --algorithm ${ALGORITHM^^} 2>&1
